# Generated by Django 5.2.7 on 2025-10-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Введите имя пользователя', max_length=50, null=True, unique=True, verbose_name='имя пользователя'),
        ),
    ]
