# Generated by Django 5.2.7 on 2025-11-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0003_alter_product_options_product_status_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('can_unpublish_product', 'Can unpublish product'), ('can_delete_product', 'Can delete product')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
